
package sistemaprogra3;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Alumnos extends javax.swing.JInternalFrame {

    private static Alumnos controlador = null;
    ArrayList<Lista> lista = new ArrayList<Lista>();
    DefaultTableModel modelo = new DefaultTableModel();
    private boolean Existe;
    private int poscicionEncontrado;
    
    
    public static  Alumnos getControlador(){
        if(controlador==null){
           return controlador = new Alumnos();
        }
          
        return controlador;
    }
    
    private  Alumnos() {
        initComponents();
        AnotherComponents();
        modelo.addColumn("ID");
        modelo.addColumn("Nombre");
        modelo.addColumn("Correo");
        modelo.addColumn("Edad");
        Tabla.setModel(modelo);

    }
    private void AnotherComponents(){
        PanelNuevoAlumno.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TxtBuscar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        BtnNuevo = new javax.swing.JButton();
        PanelNuevoAlumno = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Txtid = new javax.swing.JTextField();
        BtnGuardar = new javax.swing.JButton();
        Txtalumnonuevo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txtcorreo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtedad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jProgressBar1 = new javax.swing.JProgressBar();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        TxtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtBuscarActionPerformed(evt);
            }
        });
        TxtBuscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBuscarKeyTyped(evt);
            }
        });

        jLabel1.setText("Buscar por ID");

        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        jLabel2.setText("ID");

        Txtid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtidKeyTyped(evt);
            }
        });

        BtnGuardar.setText("Guardar");
        BtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarActionPerformed(evt);
            }
        });

        Txtalumnonuevo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtalumnonuevoKeyTyped(evt);
            }
        });

        jLabel3.setText("Nuevo Alumno");

        jLabel4.setText("Correo");

        txtedad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtedadKeyTyped(evt);
            }
        });

        jLabel5.setText("Edad");

        BtnEditar.setText("Editar");
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelNuevoAlumnoLayout = new javax.swing.GroupLayout(PanelNuevoAlumno);
        PanelNuevoAlumno.setLayout(PanelNuevoAlumnoLayout);
        PanelNuevoAlumnoLayout.setHorizontalGroup(
            PanelNuevoAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelNuevoAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNuevoAlumnoLayout.createSequentialGroup()
                        .addComponent(Txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(BtnGuardar))
                    .addGroup(PanelNuevoAlumnoLayout.createSequentialGroup()
                        .addGroup(PanelNuevoAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(Txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelNuevoAlumnoLayout.createSequentialGroup()
                        .addComponent(Txtalumnonuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNuevoAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnEliminar)))
                .addContainerGap())
        );
        PanelNuevoAlumnoLayout.setVerticalGroup(
            PanelNuevoAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelNuevoAlumnoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNuevoAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnGuardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelNuevoAlumnoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelNuevoAlumnoLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtalumnonuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Txtcorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelNuevoAlumnoLayout.createSequentialGroup()
                        .addComponent(BtnEditar)
                        .addGap(1, 1, 1)
                        .addComponent(BtnEliminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        Tabla.setColumnSelectionAllowed(true);
        Tabla.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(Tabla);
        Tabla.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
            Tabla.getColumnModel().getColumn(2).setResizable(false);
            Tabla.getColumnModel().getColumn(3).setResizable(false);
        }

        jButton1.setText("Atras");

        jButton2.setText("Siguiente");

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(jLabel1)
                            .addComponent(PanelNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnNuevo)
                            .addComponent(BtnSalir))
                        .addGap(15, 15, 15))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(34, 34, 34))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnNuevo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addComponent(PanelNuevoAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
PanelNuevoAlumno.setVisible(true);
BtnGuardar.setVisible(true);
BtnEditar.setVisible(false);
BtnEliminar.setVisible(false);
   VaciarCampos();
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarActionPerformed
        
   
     if(ValidarVacios()){
          JOptionPane.showMessageDialog(null, "Rellena todos los campos");
      }else{
          PanelNuevoAlumno.setVisible(false);
            String[] c = new String[4];
            
            c[0]=Txtid.getText();
            c[1]=Txtalumnonuevo.getText();
            c[2]=Txtcorreo.getText();
            c[3]=txtedad.getText();
            
          Lista elementos = new Lista(c[0],c[1] ,c[2] ,c[3] );
           
           lista.add(elementos);
        
          modelo.addRow(c);
               
      }
         VaciarCampos();
      
    }//GEN-LAST:event_BtnGuardarActionPerformed
    private void VaciarCampos(){
        TxtBuscar.setText("");
        Txtalumnonuevo.setText("");
        Txtcorreo.setText("");
        Txtid.setText("");
        txtedad.setText("");
    }
    private boolean ValidarVacios(){
         if(Txtalumnonuevo.getText().equals("") || Txtcorreo.getText().equals("")|| Txtid.getText().equals("")|| txtedad.getText().equals("")){
         return true;
         }
         return false;
    }
    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
this.dispose();

    }//GEN-LAST:event_BtnSalirActionPerformed

    private void TxtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtBuscarActionPerformed
       
     
        
    }//GEN-LAST:event_TxtBuscarActionPerformed

    private void TxtBuscarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBuscarKeyTyped
      
     Consumirletras(evt);
        
    }//GEN-LAST:event_TxtBuscarKeyTyped

    private void TxtalumnonuevoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtalumnonuevoKeyTyped
         ConsumirNums(evt);
    }//GEN-LAST:event_TxtalumnonuevoKeyTyped

    private void TxtidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtidKeyTyped
       Consumirletras(evt);
             
        
    }//GEN-LAST:event_TxtidKeyTyped

    private void txtedadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtedadKeyTyped
      Consumirletras(evt);
    }//GEN-LAST:event_txtedadKeyTyped

    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
         
  
        
        if(ValidarVacios()){
              JOptionPane.showMessageDialog(null, "Rellena todos los campos");
        }else{
            
             PanelNuevoAlumno.setVisible(false);
            String[] c = new String[4];
            
            c[0]=Txtid.getText();
            c[1]=Txtalumnonuevo.getText();
            c[2]=Txtcorreo.getText();
            c[3]=txtedad.getText();
            
           lista.get(poscicionEncontrado).setID(c[0]);
           lista.get(poscicionEncontrado).setNombre(c[1]);
           lista.get(poscicionEncontrado).setCorreo(c[2]);
           lista.get(poscicionEncontrado).setEdad(c[3]);
       
          
                
                modelo.setValueAt(c[0], poscicionEncontrado, 0);
                modelo.setValueAt(c[1], poscicionEncontrado, 1);
                modelo.setValueAt(c[2], poscicionEncontrado, 2);
                modelo.setValueAt(c[3], poscicionEncontrado, 3);
                
          
          
          
            
        }
        
              VaciarCampos();
    }//GEN-LAST:event_BtnEditarActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Existe=false;
        
        int  id =Integer.parseInt(TxtBuscar.getText()) ;
        
        for (int i = 0; i < lista.size(); i++) {
            
            if(id==Integer.parseInt(lista.get(i).getID())){
                Existe=true; 
                JOptionPane.showMessageDialog(null,"Encontrado"); 
                PanelNuevoAlumno.setVisible(true);
                BtnGuardar.setVisible(false);
                BtnEditar.setVisible(true);
                BtnEliminar.setVisible(true);
                
                Txtalumnonuevo.setText(lista.get(i).getNombre());
                Txtcorreo.setText(lista.get(i).getCorreo());
                Txtid.setText(lista.get(i).getID());
                txtedad.setText(lista.get(i).getEdad());
                poscicionEncontrado=i;
                break;
            }
            
        }
        
        if(!Existe){
            JOptionPane.showMessageDialog(null, "No encontrado");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        
        PanelNuevoAlumno.setVisible(false);
        lista.remove(poscicionEncontrado);
        modelo.removeRow(poscicionEncontrado);
        VaciarCampos();
        
    }//GEN-LAST:event_BtnEliminarActionPerformed
    private void Consumirletras(java.awt.event.KeyEvent evt){
         int Carac = (int)  evt.getKeyChar();
    
        if(Carac<48 || Carac>57){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
    }
    private void ConsumirNums(java.awt.event.KeyEvent evt){
        
        int Carac = (int)  evt.getKeyChar();
    
        if(Carac>=48 && Carac<=57){
            evt.consume();
            Toolkit.getDefaultToolkit().beep();
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnGuardar;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JPanel PanelNuevoAlumno;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField TxtBuscar;
    private javax.swing.JTextField Txtalumnonuevo;
    private javax.swing.JTextField Txtcorreo;
    private javax.swing.JTextField Txtid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtedad;
    // End of variables declaration//GEN-END:variables
}
