/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaprogra3;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author CARLOS BALDERRAMA
 */
public class Figuras extends javax.swing.JInternalFrame {
    private double base,altura,area;
  
    private static Figuras controlador =null;
    
    public static Figuras getFiguras(){
        if(controlador==null){
            controlador = new Figuras();
        }
        return controlador;
    }
   private  Figuras() {
        initComponents();
        this.setVisible(true);
        this.setTitle("Calcular Figuras");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TxtBASE = new javax.swing.JTextField();
        TxtALTURA = new javax.swing.JTextField();
        BtnSalir = new javax.swing.JButton();
        BtnCalcular = new javax.swing.JButton();
        TxtArea = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtResultadoRectangulo = new javax.swing.JTextField();
        TxtAncho = new javax.swing.JTextField();
        TxtLargo = new javax.swing.JTextField();
        BtnSalir2 = new javax.swing.JButton();
        BtnCalcularRectangulo = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtMasaMayor = new javax.swing.JTextField();
        TxtMasaMenor = new javax.swing.JTextField();
        TxtAlturaTrapecio = new javax.swing.JTextField();
        BtnCalcularTrapecio = new javax.swing.JButton();
        BtnSalir3 = new javax.swing.JButton();
        TxtResultadoTrapecio = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        TxtRadioCirculo = new javax.swing.JTextField();
        CalcularCirculo = new javax.swing.JButton();
        TxtResultadoCirculo = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        BtnSalir4 = new javax.swing.JButton();

        jLabel1.setText("BASE:");

        jLabel2.setText("ALTURA:");

        TxtBASE.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtBASEKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtBASEKeyTyped(evt);
            }
        });

        TxtALTURA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtALTURAKeyTyped(evt);
            }
        });

        BtnSalir.setText("SALIR");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });

        BtnCalcular.setText("CALCULAR");
        BtnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularActionPerformed(evt);
            }
        });

        TxtArea.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        TxtArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jLabel3.setText("AREA=");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(TxtArea, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(BtnSalir)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(TxtBASE)
                            .addComponent(TxtALTURA, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE))
                        .addGap(37, 37, 37)
                        .addComponent(BtnCalcular)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addComponent(TxtBASE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(BtnCalcular))
                .addGap(10, 10, 10)
                .addComponent(TxtALTURA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnSalir, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TxtArea, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        TxtArea.setEnabled(true);
        TxtArea.setEditable(false);

        jTabbedPane1.addTab("Triangulo", jPanel1);

        jLabel4.setText("ANCHO");

        jLabel5.setText("LARGO");

        jLabel6.setFont(new java.awt.Font("Consolas", 3, 14)); // NOI18N
        jLabel6.setText("Resultado=");

        TxtAncho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtAnchoKeyTyped(evt);
            }
        });

        TxtLargo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtLargoKeyTyped(evt);
            }
        });

        BtnSalir2.setText("SALIR");
        BtnSalir2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir2ActionPerformed(evt);
            }
        });

        BtnCalcularRectangulo.setText("CALCULAR");
        BtnCalcularRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularRectanguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TxtLargo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TxtAncho, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TxtResultadoRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                        .addComponent(BtnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCalcularRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(BtnCalcularRectangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TxtLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtResultadoRectangulo)
                    .addComponent(BtnSalir2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, Short.MAX_VALUE))
                .addContainerGap())
        );

        TxtResultadoRectangulo.setEditable(false);

        jTabbedPane1.addTab("Rectangulo", jPanel2);

        jLabel7.setText("MASA MAYOR");

        jLabel8.setText("MASA MENOR");

        jLabel9.setText("ALTURA");

        TxtMasaMayor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMasaMayorKeyTyped(evt);
            }
        });

        TxtMasaMenor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtMasaMenorKeyTyped(evt);
            }
        });

        TxtAlturaTrapecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtAlturaTrapecioKeyTyped(evt);
            }
        });

        BtnCalcularTrapecio.setText("CALCULAR");
        BtnCalcularTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCalcularTrapecioActionPerformed(evt);
            }
        });

        BtnSalir3.setText("SALIR");
        BtnSalir3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir3ActionPerformed(evt);
            }
        });

        TxtResultadoTrapecio.setEditable(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnSalir3))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnCalcularTrapecio)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel7)
                                .addComponent(TxtMasaMayor)
                                .addComponent(TxtAlturaTrapecio)
                                .addComponent(TxtMasaMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TxtResultadoTrapecio))
                        .addGap(0, 161, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TxtMasaMayor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TxtMasaMenor, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(16, 16, 16)
                .addComponent(TxtAlturaTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnCalcularTrapecio)
                .addGap(18, 18, 18)
                .addComponent(TxtResultadoTrapecio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(BtnSalir3)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Trapecio", jPanel3);

        jLabel10.setText("RADIO:");

        TxtRadioCirculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtRadioCirculoKeyTyped(evt);
            }
        });

        CalcularCirculo.setText("CALCULAR");
        CalcularCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcularCirculoActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 3, 14)); // NOI18N
        jLabel11.setText("RESULTADO=");

        BtnSalir4.setText("SALIR");
        BtnSalir4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalir4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TxtResultadoCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(TxtRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(CalcularCirculo))
                    .addComponent(jLabel11))
                .addContainerGap(48, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnSalir4)
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtRadioCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcularCirculo))
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(TxtResultadoCirculo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(BtnSalir4)
                .addGap(26, 26, 26))
        );

        TxtResultadoCirculo.setEditable(false);

        jTabbedPane1.addTab("Circulo", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
      this.dispose();
      TxtALTURA.setText("");
      TxtArea.setText("");
      TxtBASE.setText("");
    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularActionPerformed

        
      if(TxtALTURA.getText().isEmpty() || TxtBASE.getText().isEmpty()  )  {
          JOptionPane.showMessageDialog(null, "RELLENE TODOS LOS CAMPOS");
      }else if(TxtALTURA.getText().charAt(0)=='.' || TxtBASE.getText().charAt(0)=='.'){
                    JOptionPane.showMessageDialog(null, "NO INSERTE UN PUNTO AL INICIO");
                    
      }else{
          
          base = Double.parseDouble(TxtBASE.getText());
          altura = Double.parseDouble(TxtALTURA.getText());
          
          area = (base*altura)/2;
          TxtArea.setText(String.valueOf(area));
      }
        
    }//GEN-LAST:event_BtnCalcularActionPerformed

    private void TxtBASEKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBASEKeyPressed
    
    }//GEN-LAST:event_TxtBASEKeyPressed

    private void TxtBASEKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtBASEKeyTyped
        char c = evt.getKeyChar();
        int ascii = (int) c;
        
        if(ascii<48 && ascii!=46 || ascii >57  ){
            evt.consume();
        }
        
    }//GEN-LAST:event_TxtBASEKeyTyped

    private void TxtALTURAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtALTURAKeyTyped
         char c = evt.getKeyChar();
        int ascii = (int) c;
        
        if(ascii<48 && ascii!=46 || ascii >57  ){
            evt.consume();
        }
    }//GEN-LAST:event_TxtALTURAKeyTyped

    private void BtnSalir2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_BtnSalir2ActionPerformed

    private void BtnCalcularRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularRectanguloActionPerformed
     
        if(TxtLargo.getText().isEmpty() || TxtAncho.getText().isEmpty()  )  {
          JOptionPane.showMessageDialog(null, "RELLENE TODOS LOS CAMPOS");
      }else if(TxtLargo.getText().charAt(0)=='.' || TxtAncho.getText().charAt(0)=='.'){
                    JOptionPane.showMessageDialog(null, "NO INSERTE UN PUNTO AL INICIO");
                    
      }else{
      double largo,ancho,area;
      largo = Double.parseDouble(TxtLargo.getText());
      ancho = Double.parseDouble(TxtAncho.getText());
      area = largo * ancho;
      TxtResultadoRectangulo.setText(String.valueOf(area));
      }
        
        
    }//GEN-LAST:event_BtnCalcularRectanguloActionPerformed

    private void TxtAnchoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAnchoKeyTyped
   char c = evt.getKeyChar();
        int ascii = (int) c;
        
        if(ascii<48 && ascii!=46 || ascii >57  ){
            evt.consume();
        }      
    }//GEN-LAST:event_TxtAnchoKeyTyped

    private void TxtLargoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtLargoKeyTyped
         char c = evt.getKeyChar();
        int ascii = (int) c;
        
        if(ascii<48 && ascii!=46 || ascii >57  ){
            evt.consume();
        }
    }//GEN-LAST:event_TxtLargoKeyTyped

    private void BtnSalir3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir3ActionPerformed
this.dispose();    }//GEN-LAST:event_BtnSalir3ActionPerformed

    private void BtnCalcularTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCalcularTrapecioActionPerformed
       
        if(TxtMasaMayor.getText().isEmpty() || TxtMasaMenor.getText().isEmpty() || TxtAlturaTrapecio.getText().isEmpty()  )  {
          JOptionPane.showMessageDialog(null, "RELLENE TODOS LOS CAMPOS");
      }else if(TxtMasaMayor.getText().charAt(0)=='.' || TxtMasaMayor.getText().charAt(0)=='.' || TxtAlturaTrapecio.getText().charAt(0)=='.'){
                    JOptionPane.showMessageDialog(null, "NO INSERTE UN PUNTO AL INICIO");
                    
      }else{
      double BMayor,BMenor,Altura,area;
      BMayor = Double.parseDouble(TxtMasaMayor.getText());
      BMenor = Double.parseDouble(TxtMasaMenor.getText());
      Altura = Double.parseDouble(TxtAlturaTrapecio.getText());
      area = ((BMayor+BMenor)/2)*Altura;
      TxtResultadoTrapecio.setText(String.valueOf(area));
      }
    }//GEN-LAST:event_BtnCalcularTrapecioActionPerformed

    private void TxtRadioCirculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtRadioCirculoKeyTyped
      
       char c = evt.getKeyChar();
        int ascii = (int) c;
        
        if(ascii<48 && ascii!=46 || ascii >57  ){
            evt.consume();
        }      
        
        
        
    }//GEN-LAST:event_TxtRadioCirculoKeyTyped

    private void TxtMasaMayorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMasaMayorKeyTyped
        char c = evt.getKeyChar();
        int ascii = (int) c;
        
        if(ascii<48 && ascii!=46 || ascii >57  ){
            evt.consume();
        }      
    }//GEN-LAST:event_TxtMasaMayorKeyTyped

    private void TxtMasaMenorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMasaMenorKeyTyped
       char c = evt.getKeyChar();
        int ascii = (int) c;
        
        if(ascii<48 && ascii!=46 || ascii >57  ){
            evt.consume();
        }      
    }//GEN-LAST:event_TxtMasaMenorKeyTyped

    private void TxtAlturaTrapecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtAlturaTrapecioKeyTyped
        char c = evt.getKeyChar();
        int ascii = (int) c;
        
        if(ascii<48 && ascii!=46 || ascii >57  ){
            evt.consume();
        }      
    }//GEN-LAST:event_TxtAlturaTrapecioKeyTyped

    private void CalcularCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcularCirculoActionPerformed
       if(TxtRadioCirculo.getText().isEmpty()   )  {
          JOptionPane.showMessageDialog(null, "RELLENE TODOS LOS CAMPOS");
      }else if(TxtRadioCirculo.getText().charAt(0)=='.' ){
                    JOptionPane.showMessageDialog(null, "NO INSERTE UN PUNTO AL INICIO");
      }else{
          
        double radio = Double.parseDouble(TxtRadioCirculo.getText());
        double area = Math.PI* Math.pow(radio, 2);
        
        DecimalFormat DF = new DecimalFormat("#0.00");
        TxtResultadoCirculo.setText(String.valueOf(DF.format(area)));
      }
        
        
      
    }//GEN-LAST:event_CalcularCirculoActionPerformed

    private void BtnSalir4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalir4ActionPerformed
      this.dispose();
    
    }//GEN-LAST:event_BtnSalir4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCalcular;
    private javax.swing.JButton BtnCalcularRectangulo;
    private javax.swing.JButton BtnCalcularTrapecio;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnSalir2;
    private javax.swing.JButton BtnSalir3;
    private javax.swing.JButton BtnSalir4;
    private javax.swing.JButton CalcularCirculo;
    private javax.swing.JTextField TxtALTURA;
    private javax.swing.JTextField TxtAlturaTrapecio;
    private javax.swing.JTextField TxtAncho;
    private javax.swing.JTextField TxtArea;
    private javax.swing.JTextField TxtBASE;
    private javax.swing.JTextField TxtLargo;
    private javax.swing.JTextField TxtMasaMayor;
    private javax.swing.JTextField TxtMasaMenor;
    private javax.swing.JTextField TxtRadioCirculo;
    private javax.swing.JTextField TxtResultadoCirculo;
    private javax.swing.JTextField TxtResultadoRectangulo;
    private javax.swing.JTextField TxtResultadoTrapecio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
