/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Libros;

import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.table.DefaultTableModel;
import Libros.Libro;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

public class InterfazLibro extends javax.swing.JInternalFrame {

    private static InterfazLibro controlador = null;
    private int poscicion = -1;
    ArrayList<Libro> lista = new ArrayList<Libro>();
    DefaultTableModel modelo = new DefaultTableModel() {
        public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
    };
    private boolean Existe;
    private int poscicionEncontrado;
    File f = new File("src\\Archivo\\Libros.txt");

    private InterfazLibro() {
        initComponents();

        modelo.addColumn("Titulo");
        modelo.addColumn("Editorial");
        modelo.addColumn("Autor");
        modelo.addColumn("Año");

        Tabla.setModel(modelo);
        BtnActualizarLista.setVisible(false);
        BtnActualizarLista.doClick();
    }

    public static InterfazLibro getControlador() {

        if (controlador == null) {
            controlador = new InterfazLibro();
        }
        return controlador;
    }

    public void ActualizarTablaDesdeOtraClase() {
        BtnActualizarLista.doClick();
    }
    public void ActualizarTxtDesdeOtraClase(){
        ActualizarTxt();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        BtnNuevo = new javax.swing.JButton();
        BtnFiltros = new javax.swing.JButton();
        BtnEditar = new javax.swing.JButton();
        BtnEliminar = new javax.swing.JButton();
        BtnActualizarLista = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);

        Tabla.setModel(modelo);
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        BtnNuevo.setText("Nuevo");
        BtnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNuevoActionPerformed(evt);
            }
        });

        BtnFiltros.setText("Buscar");
        BtnFiltros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnFiltrosActionPerformed(evt);
            }
        });

        BtnEditar.setText("Editar");
        BtnEditar.setEnabled(false);
        BtnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEditarActionPerformed(evt);
            }
        });

        BtnEliminar.setText("Eliminar");
        BtnEliminar.setEnabled(false);
        BtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarActionPerformed(evt);
            }
        });

        BtnActualizarLista.setText("Actualizar lista");
        BtnActualizarLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnActualizarListaActionPerformed(evt);
            }
        });

        jLabel2.setText("Filtros");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(220, 220, 220)
                        .addComponent(BtnActualizarLista)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(197, 197, 197)
                        .addComponent(BtnFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(159, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnActualizarLista)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(BtnFiltros, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnEliminar)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNuevoActionPerformed
        Agregar add = new Agregar(new JFrame(), true);
        add.setVisible(true);
    }//GEN-LAST:event_BtnNuevoActionPerformed

    private void BtnFiltrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnFiltrosActionPerformed
       Filtros f = new Filtros(new JFrame(),true);
        f.setVisible(true);
    }//GEN-LAST:event_BtnFiltrosActionPerformed

    private void BtnActualizarListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnActualizarListaActionPerformed
        modelo.setRowCount(0);
        try {
            FileReader FR = new FileReader(f.getAbsoluteFile());
            BufferedReader BR = new BufferedReader(FR);
            String text = "";

            while ((text = BR.readLine()) != null) {

                String[] split = text.split(";");

                modelo.addRow(split);
            }
            BR.close();
        } catch (IOException e) {

        }

    }//GEN-LAST:event_BtnActualizarListaActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        poscicion = Tabla.rowAtPoint(evt.getPoint());
        BtnEditar.setEnabled(true);
        BtnEliminar.setEnabled(true);
    }//GEN-LAST:event_TablaMouseClicked

    private void BtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarActionPerformed
        modelo.removeRow(poscicion);
        ActualizarTxt();
      BtnActualizarLista.doClick();
     DesabilitarBotonesEditarYEliminar();
    }//GEN-LAST:event_BtnEliminarActionPerformed
     
    
    public void DesabilitarBotonesEditarYEliminar(){
      BtnEditar.setEnabled(false);
      BtnEliminar.setEnabled(false);
    }
    private void BtnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEditarActionPerformed
      Editar edit = new Editar(new JFrame(),true,poscicion);
      edit.setVisible(true);
    }//GEN-LAST:event_BtnEditarActionPerformed
     private void  ActualizarTxt(){
         
       
        File f = new File("src\\Archivo\\Libros.txt"); f.delete();
    
        try {
            f.createNewFile();
            FileWriter FW = new FileWriter(f.getAbsoluteFile(), true);
            BufferedWriter BW = new BufferedWriter(FW);

            for (int i = 0; i < modelo.getRowCount(); i++) {
                for (int j = 0; j < modelo.getColumnCount(); j++) {
                  String registro =String.valueOf(modelo.getValueAt(i, j))  ;
                    BW.write(registro+";");
                }
                  BW.newLine();
            }
           
            
            BW.close();

        } catch (IOException ex) {
            Logger.getLogger(Agregar.class.getName()).log(Level.SEVERE, null, ex);
        }
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnActualizarLista;
    private javax.swing.JButton BtnEditar;
    private javax.swing.JButton BtnEliminar;
    private javax.swing.JButton BtnFiltros;
    private javax.swing.JButton BtnNuevo;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
